### ISSUE TITLE
No #define greenVal?

### ISSUE THREAD

**Issue by Tookmund** [WoodsonRobotics/Botball-2015#1]
ping @markagrios 

Line twelve of Martha/main.c reads:

``` c
while(get_object_count(greenVal) == 0 && get_object_count(redVal) == 0) {
```

While header.h only contains:

``` c
#define pinkVal 0
#define redVal 1
```

Do we need a greenVal or is that supposed to be `pinkVal`?

**Comment by markagrios** [comment]
My bad, it's actually supposed to be green and red, no pink.
